### ISSUE TITLE
Initially support only book page and simple multiple questions

### ISSUE THREAD

**Issue by sgoshorn** [CCALI/caw#1]
Leave the harder page types for later.

**Comment by emasters** [comment]
Start with 3 page types:
* Topics - used for Contents page
* Book Page - used for general text, including Introduction and Conclusion
* Multiple Choice - the questions, the answers and feedback.

**Comment by sgoshorn** [comment]
- [x] Multiple choice - one right, and N wrong /distractors in random order
- [x] True/False
