### ISSUE TITLE
Ending message for quizzes

### ISSUE THREAD

**Issue by sgoshorn** [CCALI/caw#10]
Add a special book page after the quiz questions with a generic message instructing students to Finalize their scores.

**Comment by sgoshorn** [comment]
Should there be an automatic page or just let author add instructions to their custom Conclusion section?

**Comment by dquentel** [comment]
If we want the student to know he needs to finalize his score, I think we have to include that language. I don't think that act would be intuitive to the prof. 

Maybe an auto page with default language that prof can edit? or are we now getting too complex?

**Comment by emasters** [comment]
Do they need to finalize their scores? Right now we do nothing to force a finalized score. I guess if one was needed I go for a generic reminder. I feel like we're teetering on the edge of some sort of CALI Author Lite that is only to unduly delay releasing QuizWright while we chase features.

**Comment by sgoshorn** [comment]
They don't need to finalize. I'm thinking more of the fact there's no explicit 'You're done, you can go now' type of message. After the last question they end up back on the TOC and may wonder what to do next. I'll leave it up to the author for now. There's a place they can add final instructions, if they feel the need. Those instructions appear after the student goes to the next page after the last question.

**Comment by johnmayer** [comment]
I don't think we need FINALIZE SCORE. When they finish the the quiz, they are finished.  Are we already allowing going backward to re-answer questions?  Can they skip questions and come back?  These are features of summative assessment systems - exams - not quizzes usually.  I say no backsies, no skipping questions and answering the last questions==finalizing score.  We can capabilities later.

**Comment by dquentel** [comment]
If they don't *need* to finalize then I agree -- let's not add it.
