### ISSUE TITLE
Change the button text inside Lesson Viewer from "LessonPast" to "Analytics"

### ISSUE THREAD

**Issue by johnmayer** [CCALI/caw#105]
I like the terms LessonLive/LessonPast, but they are confusing to faculty IMHO.  Suggest changing the button text from "LessonPast" to "Analytics". See pic 

![image](https://user-images.githubusercontent.com/2457935/30649261-69d9d228-9de5-11e7-87aa-4e5724d1685b.png)

**Comment by sgoshorn** [comment]
I agree that Lesson Past is confusing but do faculty know what "Analytics" means? What term would make most sense to them? Maybe just "Assessment"?

**Comment by emasters** [comment]
The Lesson Past report really is analytics. It provides a pretty thorough analysis of how students individually and as a group performed on a given Lesson.
I think law faculty can learn a new word here.

**Comment by sgoshorn** [comment]
Analytics it shall be.

**Comment by emasters** [comment]
But let's hold that change until after the semester ends. The changes to LL and AP will be deployed between Christmas and New Year's. Don;t want to spring new terminology on folks this late in the semester.

**Comment by sgoshorn** [comment]
It's on d7 already. Too fast..
