### ISSUE TITLE
Add teacher note for shared questions

### ISSUE THREAD

**Issue by sgoshorn** [CCALI/caw#23]
When sharing a question the author may want to include a note to other teachers. 
An example from Deb Cohen: The author knows students regularly choose a particular wrong choice for some question. The author includes this choice knowing this and includes a note about this so teachers understand the question's design and teaching purpose.

**Comment by emasters** [comment]
This is only useful for sharing, which we aren't planning until later in the Fall. This may also be a feature creep thing. While trick questions are fine for Lessons, they tend toward evil in formative assessment. Teachers should be writing questions to find out what students know, not what they don't know.

**Comment by sgoshorn** [comment]
Added but it's hidden under an collapsible.
