### ISSUE TITLE
Handling HTML in input fields

### ISSUE THREAD

**Issue by emasters** [CCALI/caw#26]
I tried putting HTML into the intro page field on the new quiz form and it broke the whole quiz. It created an empty quiz that I can't edit properly or delete. 
I understand that we don't want to allow HTML in the quizzes yet but we need to add a warning or do some handling of HTML that is entered to prevent it from breaking the creation process.

**Comment by emasters** [comment]
![qwcreatenewhtml20170531](https://cloud.githubusercontent.com/assets/741239/26645756/425aadca-4607-11e7-901e-0af4fec28385.PNG)

**Comment by emasters** [comment]
![qwcreatequizhtmlbadlist20170531](https://cloud.githubusercontent.com/assets/741239/26645936/cffc05de-4607-11e7-8631-fece9a870d20.PNG)

This is what I see after adding HTML into Intro or Conclusion page. Since it's not expecting HTML it just makes it crash quietly.

**Comment by sgoshorn** [comment]
I think it's the double quotes, not HTML.  I think I'm missing a paramquery style update for quiz creation.
