### ISSUE TITLE
Suggest removing the CALI Teaching Resources section 

### ISSUE THREAD

**Issue by johnmayer** [CCALI/caw#80]
The CALI Teaching Resources (lower, left of the screen) are unrelated to QuizWright and are a distraction.  I suggest that we remove them altogether.

**Comment by emasters** [comment]
I don't think letting law faculty know about the other resources we provide them is a distraction. QuizWright doesn't exist in a vacuum and it needs to be shown as part of a wide range of tools teachers can use to.

**Comment by sgoshorn** [comment]
Could we make custom landing pages for each that explain how QuizWright could specifically be used with them?
