### ISSUE TITLE
Add published indicator to Quiz Details page after published to Drupal

### ISSUE THREAD

**Issue by emasters** [CCALI/caw#89]
When the publish button is clicked everything shifts to the new Drupal tab to complete the save. When I return to the QuizWright page there is no indication that I just published the quiz. 
Suggestions:

- after publish is clicked move the QW app back to the quiz list page which should reflect the newly published quiz's status
- add a modal pop-up to the details page that lets the teacher know the publishing was successful. Click on OK to get back to the app.

**Comment by emasters** [comment]
@sgoshorn This needs a fix ASAP. Right now when I publish a quiz there's no indication that it's published on the quiz detail page. I think the best approach is to move QW to the quiz list page since it will have the publish info on it.

**Comment by sgoshorn** [comment]
Added a 'Publishing...' notice after you hit the publish button. After a few seconds (time for AP to fill in the db) it switches to the Quiz list and hilites the published quiz row.
